services:
  api:
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile
    depends_on:
      - eshopdb  

  eshopdb:
    container_name: eshopdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EShopDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_eshopdb:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d EShopDb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s